### ISSUE TITLE
retry failure 

### ISSUE THREAD

**Issue by coinhosting** [kneodev/ksmppd#100]
Hi,

is this possible to set retry for failure sms with different smsc

example : if we have smsc1 and smsc2 an message submit to smsc1 will retry with smsc2 (without send any dlr to esme) incase of undelivered  

thanks

**Comment by ib1corp** [comment]
Hi @coinhosting , you had a TPS issue earlier in one of your old posts.

How did you fix it? we are facing similar issue. not able to get beyond 30 tps. tried everything possible.
please suggest how you got over this. im using kannel 1.4.4 (this was compiled in 2015 and running since then)

**Comment by coinhosting** [comment]
Hi,

You have TPS issue at ESME end or Smpp gateway end.

Thanks

**Comment by ib1corp** [comment]
the ESME is my own kannel setup on the other server that uses kannel, same settings.
It works well with all other smpp providers, even if i submit to an smpp taken from opensmppbox it works well. but if i submit to ksmppd, its not processing more that 30-40 tps.
i had set 400 tps on the user table with 4 session, still having same issue.
using db routing. Its a 8gb ram, 4 core, cent os.

not sure where is the issue.

**Comment by coinhosting** [comment]
please share your esme config so we can more help

**Comment by ib1corp** [comment]
i changed the server to a better one. its working fine now. thanks.

**Comment by coinhosting** [comment]
Dear Donald Jackson,

@ib1corp over comment this issue 

Correct questions was

is this possible to set retry for failure sms with different smsc

example : if we have smsc1 and smsc2 an message submit to smsc1 will retry with smsc2 (without send any dlr to esme) incase of undelivered

Which requires your input

thanks

**Comment by donald-jackson** [comment]
@coinhosting No this is not a feature, more of a user level requirement, you could implement a DLR listener and automate this yourself.
