### ISSUE TITLE
ksmppd installation issue:

### ISSUE THREAD

**Issue by ib1corp** [kneodev/ksmppd#101]
im having difficulty to install ksmppd.
using kannel 1.4.5 stable release.

root@smpp-ubuntu-s-2vcpu-4gb-1-01:# git clone https://github.com/kneodev/ksmppd.git
root@smpp-ubuntu-s-2vcpu-4gb-1-01:# cd ksmppd
root@smpp-ubuntu-s-2vcpu-4gb-1-01:~/ksmppd# ./bootstrap.sh
**You need svn on your $PATH to build ksmppd**

where am i going wrong? someone please help.

**Comment by ib1corp** [comment]
hi @kneodev  , @donald-jackson 

""You need svn on your $PATH to build ksmppd""
how to get over this issue?

please help.

**Comment by coinhosting** [comment]
install svn (subversion) in your server and try again

**Comment by ib1corp** [comment]
thanks

**Comment by veduyu** [comment]
@ib1corp how you install svn on your server please help.
