### ISSUE TITLE
regarding ksmppd log.

### ISSUE THREAD

**Issue by veduyu** [kneodev/ksmppd#102]
how can i log no-credit and other ksmppd generated logs on sqlbox?

**Comment by veduyu** [comment]
@kneodev please relpy.

**Comment by donald-jackson** [comment]
you can't, you need to use a custom router if you want to log errors in sqlbox

**Comment by veduyu** [comment]
@donald-jackson ok.. actually i dont want to use sqlbox for tracking all the message..is there any other way so that i can track all the messages in the database without using sqlbox..
