### ISSUE TITLE
Throughput Issue

### ISSUE THREAD

**Issue by veduyu** [kneodev/ksmppd#104]
Hello @donald-jackson i'am using ksmppd with two sqlbox connected with kannel, but when i tested with fake smsc iam getting tps of 20-25. what should i do. my server configuration:-

MEMORY | VCPUS | SSD DISK | TRANSFER
16 GB     | 6 vCPUs | 320 GB    | 6 TB

iam also attaching my configuration file.
Please help??

[configuratin.odt.zip](https://github.com/kneodev/ksmppd/files/2257273/configuratin.odt.zip)

**Comment by donald-jackson** [comment]
how are you testing

**Comment by veduyu** [comment]
i have a ksmppd instance running on my another server with simulate_permanent_failure=1 and throughput=100 and i'am connecting that route from my another server for which iam testing rith now.

**Comment by veduyu** [comment]
#right now

**Comment by veduyu** [comment]
i also tried it with real smsc, but still iam getting the tps of 20-30!!
Please help me sir

**Comment by donald-jackson** [comment]
answer the question, else I can't really help you

**Comment by veduyu** [comment]
sir my connection is like this | bererbox(15000)---sqlbox(13011)---sqlbox(13005)---ksmppd(14010)|
and i have created a user through ksmppd which uses database routing, the problem is that the client is not getting the tps that i allocated to him, in the smpp_user table the throughput is 100 with bind 5 but still the client very less throughput.

**Comment by donald-jackson** [comment]
ok but this is not a controlled test? How do you know your client is sending fast enough?

**Comment by veduyu** [comment]
Because he is facing this issue on my esme account only...he showed on remote desktop, and the other esme is giving him 70-80tps.

**Comment by donald-jackson** [comment]
There are many factors that go into performance, window sizing, smpp versions, etc. Do a controlled test and then you can isolate issues. ksmppd can easily do over >1000 msgs/sec so the issue is most likely with your client or your server configuration

**Comment by veduyu** [comment]
Thanku. i will properly test and let u know sir :)

**Comment by ib1corp** [comment]
Hi @veduyu , i had the same issue the first time i started using, not getting beyond 23-30 tps, i was usign centos 6 and kannel 1.4.4 when i got this issue, not sure what was the reason, later i took a fresh server with ubuntu 18.04, 4core, 8gb ram, and installed kannel 1.4.5 ... ksmppd > sqlbox > bearerbox .. able to get around 1000tps, works like a charm.

**Comment by rajeev36** [comment]
@veduyu / @ib1corp , 
can you please share any sample configuration.
I'm trying ksmppd > sqlbox > bearerbox on ubuntu 18.04, 4core, 8gb ram . But not able to achieve throughput.
please help.
