### ISSUE TITLE
Issue with Submission of sms 

### ISSUE THREAD

**Issue by rajesh6115** [kneodev/ksmppd#107]
we are experiencing some submit failed with status code 0x00000008.
I observer it's happening when 

1. SMS is not routable.
2. when the provider connection in bearerbox is down for some time.

for case 1 its acceptable as it may lead to non-consumable SMS.
but for case 2 I think it should queue in the database for later delivery instead of rejecting SMS.

**Comment by donald-jackson** [comment]
This will only be if the gateway is dead/stopped. Make sure you only keep active/re-connecting gateways as these are rejected on the bearerbox level and will fail no matter which smpp/smsbox you use.
