### ISSUE TITLE
done date time  is wrong in DLR content

### ISSUE THREAD

**Issue by rajesh6115** [kneodev/ksmppd#108]
I had this issue when we got delayed DLR message. But SMS Got Delivered immediately.
operator dlr message is as follows:
id:ce5bc5a9-4f7d-4282-9244-2e1022a9335c sub:000 dlvrd:000 submit date:180903120815 done date:180903120816 DELIVRD err:000 Text:
but my client got : 
id:7d093bfa-4d65-4757-b0bb-177fc9d0a038 sub:001 dlvrd:001 submit date:180903120232 done date:180903121447 stat:DELIVRD err:000 text:
**Also verified That I got That DLR in 12:14:47 according to log.**
which is wrong? we should pass what we got from operator for done time.

According to me it should pass done date from operator text content. So I expect it to be
id:7d093bfa-4d65-4757-b0bb-177fc9d0a038 sub:001 dlvrd:001 submit date:180903120232 done date:180903120816 stat:DELIVRD err:000 text:

**Comment by donald-jackson** [comment]
Not really, ksmppd is an aggregation system, its job is to abstract operator error codes so your customer don't have to deal with the complexities of each one.

**Comment by rajesh6115** [comment]
But What About **done date**?
currently, operator error codes are passing as it is.
the sms status (i.e stat) is modified to the standard one as per smpp spec.
