### ISSUE TITLE
Delivery Queue at smppbox end

### ISSUE THREAD

**Issue by coinhosting** [kneodev/ksmppd#110]
Hi,

we face this issue in every 2-3 days that DLR's queued at smppbox end at kannel page and process very slow to esme clients.

please find attached screen shot and help us to resolve issue 

thanks  
![image](https://user-images.githubusercontent.com/25124293/45345178-2b081400-b5c3-11e8-8e7e-1278c872786f.png)

![image](https://user-images.githubusercontent.com/25124293/45345204-3d824d80-b5c3-11e8-8727-dd8b9f647f09.png)

**Comment by donald-jackson** [comment]
You have a misbehaving ESME, make sure you specify smsbox-max-pending

**Comment by coinhosting** [comment]
Hi,

thanks for your update !!

can you please confirm "smsbox-max-pending" 

1. this will apply for each users or overall users
2. we are using sqlbox will this work 
3. what is recommended value for same 

Thanks
