### ISSUE TITLE
ksmppd hang 

### ISSUE THREAD

**Issue by coinhosting** [kneodev/ksmppd#112]
Hi,

we are facing an different type of issue that we start ksmppd using command ./smpp/ksmppd and terminal start given output of process everything works fine as normal but once we close terminal ksmppd incoming/outgoing processed getting stuck.

i mean all esme still connected but not able to sent / receive and sms/dlr can you please suggest any solution for same 

thanks

**Comment by x3dph** [comment]
try use screen or nohup , run the ./smpp/ksmppd inside it before you screen -d (detach)

**Comment by donald-jackson** [comment]
fixed in e40daa5195b578b2f89e7d2c80b90f2516beca11
