### ISSUE TITLE
DLR returns

### ISSUE THREAD

**Issue by x3dph** [kneodev/ksmppd#114]
my setup is SMPP Client <=> KSMPPD <=> HTTP Gateway 
how can i return the delivery receipt to SMPP Client?  what are the response in the HTTP Gateway needed to return DLR, or how can i push back the DLR. 

thank you

_Originally posted by @x3dph in https://github.com/kneodev/ksmppd/issues/94#issuecomment-433406849_

**Comment by rajesh6115** [comment]
> SMPP Client <=> KSMPPD <=> HTTP Gateway

I think this is not Possible, Instead of this It may be
SMPP Client <=> KSMPPD <=> Bearerbox <=> HTTP Gateway

**Comment by nmtbk** [comment]
How to convert SMPP to HTTP? Appreciate for you help. Thanks.

**Comment by rajesh6115** [comment]
> How to convert SMPP to HTTP? Appreciate for you help. Thanks.

1. configure http based smsc in bearerbox.
2. Test the http route working using send-sms(smsbox)
3. use same smsc for all clients of kasmppd. 
**Now this way all smpp requests will come to your http server, do all magic.** 
4. then send dlr to http smsc again for passing dlr to your smpp clients.
### Done

**Comment by x3dph** [comment]
> 4. then send dlr to http smsc again for passing dlr to your smpp clients.
- can you show sample how to send dlr to http smsc. thanks

**Comment by x3dph** [comment]
how can http return the dlr to the smpp clients? can you help paste sample url/syntax to return to ksmppd to smpp clients, thanks

**Comment by rajesh6115** [comment]
> how can http return the dlr to the smpp clients? can you help paste sample url/syntax to return to ksmppd to smpp clients, thanks

`localhost:3015/sms?username=rajeshx6115&password=xxx&dlr-mid=MKQ6GmVtZJgIfo3WbBvxEz4CUkYSAiF1&to=919853493896&dlr-error=0&text=id:MKQ6GmVtZJgIfo3WbBvxEz4CUkYSAiF1 sub:001 dlvrd:001 submit date:181222100335 done date:181222100336 stat:DELIVRD err:000 text:&dlr-mask=1`

my http smsc config is as below
```
group = smsc
smsc = http
system-type = generic
smsc-id = http-smsc
port = 3015
.
.
.
```
NOTE:
1. port number for my dlr request and http smsc port are same.
2. Also text param contains a proper formatted dlr like in DeliverSm Pdu DLR Message
3. dlr-mid should be same as foreign id, as this is the ID which map http sms to bearerbox message
4. Please test your HTTP SMSC using smsbox(sendsms) method, before trying to use in ksmppd.

**Comment by x3dph** [comment]
thanks for your help

**Comment by AllURNeed** [comment]
Hello i am using this parameters,

can you please help me , how to send SMS Deliverd dlr to ksmppd client from kannel , 


group = smsc
smsc = http
smsc-id = httpApi
system-type = generic
send-url = "http://I.P/gsim.php?mbl=%p&msg=%b&coding=%c"
status-success-regex = "ok"
allowed-smsc-id="httpApi"
generic-message-sent = "%I"
alt-charset="UTF-8"
#alt-charset = "ASCII"
