### ISSUE TITLE
Not able to install ksmpp

### ISSUE THREAD

**Issue by veduyu** [kneodev/ksmppd#115]
Dear @donald-jackson i'am facing the following issue which installing ksmppd on ubuntu 18.04

root@ubuntu-s-4vcpu-8gb-blr1-01:/opt/ksmppd-master# ./bootstrap.sh 
You need svn on your $PATH to build ksmppd

Please help?

**Comment by rajesh6115** [comment]
Install svn first, then try again
`sudo apt-get install subversion`
