### ISSUE TITLE
./bootstrap.sh DB Error

### ISSUE THREAD

**Issue by bhavesh53** [kneodev/ksmppd#117]
getting error while ./boostrap.sh command 

> Configuring DB support ...
checking whether to compile with MySQL support... searching
checking for mysql_config... /usr/bin/mysql_config
checking mysql version... 10.3.13
checking mysql reentrant libs... -L/usr/lib64/ -lmariadb -lz -ldl -lm -lpthread -lssl -lcrypto
checking for mysql_init in -lmysqlclient_r... no
checking mysql libs... -L/usr/lib64/ -lmariadb -lz -ldl -lm -lpthread -lssl -lcrypto
checking for mysql_init in -lmysqlclient... no
configure: error: Unable to find MySQL client libraries
Fatal error occurred executing ./configure --prefix=/opt/ksmppd/build --with-mysql --enable-ssl --enable-start-stop-daemon

**Comment by voicecomms** [comment]
Please install MYSQL devel as well this will resolve the issue

Regards 
CJ






---- On Wed, 27 Mar 2019 16:56:11 +0530 bhavesh53 <mailto:notifications@github.com> wrote ----



getting error while ./boostrap.sh command


Configuring DB support ...

 checking whether to compile with MySQL support... searching

 checking for mysql_config... /usr/bin/mysql_config

 checking mysql version... 10.3.13

 checking mysql reentrant libs... -L/usr/lib64/ -lmariadb -lz -ldl -lm -lpthread -lssl -lcrypto

 checking for mysql_init in -lmysqlclient_r... no

 checking mysql libs... -L/usr/lib64/ -lmariadb -lz -ldl -lm -lpthread -lssl -lcrypto

 checking for mysql_init in -lmysqlclient... no

 configure: error: Unable to find MySQL client libraries

 Fatal error occurred executing ./configure --prefix=/opt/ksmppd/build --with-mysql --enable-ssl --enable-start-stop-daemon
