### ISSUE TITLE
unbind doesn't decrease binds counter

### ISSUE THREAD

**Issue by Enzo-life** [kneodev/ksmppd#118]
Good day. 

I'm new to this software, just trying out and testing. Many thanks to author for this simple and powerfull tool.

As i see, after sending unbind command esme can't reconnect quickly because binds counter didn't decremented. I don't know if it's normal logic for smpp, but our sms center have many clients which bind each time when they need to send sms, so they can connect quite often. 

It is not a problem for us when our current smpp server decrease binds counter when receive unbind command. But it will not work using ksmppd. Is it bug or feature? Can it be fixed?

By the way, when esme will try to bind after unbind, it will be even banned for a while :)

**Comment by donald-jackson** [comment]
fixed in e40daa5195b578b2f89e7d2c80b90f2516beca11
