### ISSUE TITLE
rebuild-user method like rebuild-routes

### ISSUE THREAD

**Issue by m-faraz** [kneodev/ksmppd#124]
Is it possible to have a rebuild-user method just like the rebuild-routes method. We recently had to update just the throughput of a single user and to achieve that, we had to restart ksmppd.

**Comment by donald-jackson** [comment]
This isn't needed as throughput isn't cached as with other methods.

You can unbind the user and the next time they connect they will receive updated throughput setting.

**Comment by m-faraz** [comment]
Thanks @donald-jackson . That was exactly what we had done, just forgot to update it here.
