### ISSUE TITLE
SMPP Server Installation Issue

### ISSUE THREAD

**Issue by adamilleriam** [kneodev/ksmppd#127]
Hello there,
I'm totally new in smpp sector. I don't have that much knowledge about SMPP installation so i follow the git repository https://github.com/kneodev/ksmppd for installation. But while i run bootstrap.sh file i'm facing "Unable to find MySQL client libraries" error. i installed mysql client and create a soft link between libmysqlclient.so and libmysqlclient_r.so. I also installed zlib1g as per solution of https://redmine.kannel.org/issues/497.

My OS - Ubuntu 16.04

Full Error
-------------------------------------------------------------------------------------------------------------------------------------------------------------

Fetching external item into 'kannel-svn-trunk/addons/sqlbox':
Checked out external at revision 58.

Fetching external item into 'kannel-svn-trunk/addons/opensmppbox':
Checked out external at revision 94.

Checked out revision 5297.
+ export WANT_AUTOMAKE=1.8
+ which glibtoolize
+
+ libtoolize --copy --automake --force
+ aclocal
aclocal: warning: autoconf input should be named 'configure.ac', not 'configure.in'
+ autoheader
+ autoconf
+ automake --add-missing --copy --gnu
automake: warning: autoconf input should be named 'configure.ac', not 'configure.in'
configure.in:88: warning: AM_INIT_AUTOMAKE: two- and three-arguments forms are deprecated.  For more info, see:
configure.in:88: http://www.gnu.org/software/automake/manual/automake.html#Modernize-AM_005fINIT_005fAUTOMAKE-invocation
configure.in:91: installing './compile'
configure.in:88: installing './missing'
checks/Makefile.am: installing './depcomp'
automake: warning: autoconf input should be named 'configure.ac', not 'configure.in'
checking svn checkout revision... 5297M

Configuring for Kannel gateway version svn-r5297M ...
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes

Running system checks ...
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking for gcc option to accept ISO C99... none needed
checking for bison... no
checking for byacc... no
checking for flex... no
checking for lex... no
checking for convert... /usr/bin/convert
checking for perl... /usr/bin/perl
checking for inline... inline
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking size of short... 2
checking size of int... 4
checking size of long... 8
checking size of long long... 8
checking for log in -lm... yes
checking for accept in -lsocket... no
checking for inet_ntoa in -lnsl... yes
checking for inet_ntop in -lresolv... yes
checking for inet_ntop in -lbind... no
checking for pthread_exit in -lpthread... yes
checking for libiconv in -liconv... no
checking for ANSI C header files... (cached) yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for sys/types.h... (cached) yes
checking for unistd.h... (cached) yes
checking sys/poll.h usability... yes
checking sys/poll.h presence... yes
checking for sys/poll.h... yes
checking pthread.h usability... yes
checking pthread.h presence... yes
checking for pthread.h... yes
checking getopt.h usability... yes
checking getopt.h presence... yes
checking for getopt.h... yes
checking syslog.h usability... yes
checking syslog.h presence... yes
checking for syslog.h... yes
checking iconv.h usability... yes
checking iconv.h presence... yes
checking for iconv.h... yes
checking zlib.h usability... yes
checking zlib.h presence... yes
checking for zlib.h... yes
checking execinfo.h usability... yes
checking execinfo.h presence... yes
checking for execinfo.h... yes
checking for stdlib.h... (cached) yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking sys/sockio.h usability... no
checking sys/sockio.h presence... no
checking for sys/sockio.h... no
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking for net/if.h... yes
checking sys/ucontext.h usability... yes
checking sys/ucontext.h presence... yes
checking for sys/ucontext.h... yes
checking for ld used by gcc... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking for shared library run path origin... done
checking for iconv... yes
checking for working iconv... yes
checking for iconv declaration...
         extern size_t iconv (iconv_t cd, char * *inbuf, size_t *inbytesleft, char * *outbuf, size_t *outbytesleft);
checking for gettimeofday... yes
checking for select... yes
checking for socket... yes
checking for strdup... yes
checking for getopt_long... yes
checking for localtime_r... yes
checking for gmtime_r... yes
checking for backtrace... yes
checking for srandom... yes
checking for strtoll... yes
checking for strtoq... yes
checking for setpriority... yes
checking for initgroups... yes
checking for getopt... yes
checking for gethostbyname_r... yes
checking for which type of gethostbyname_r... 6
checking for socklen_t in <sys/socket.h>... yes
checking for getopt in <stdio.h>... no
checking for getopt in <unistd.h>... yes
checking ftw.h usability... yes
checking ftw.h presence... yes
checking for ftw.h... yes
checking for nftw... yes
checking regex.h usability... yes
checking regex.h presence... yes
checking for regex.h... yes
checking for regcomp... yes

Checking for POSIX threads support ...
checking for working pthreads... yes
checking for pthread_spinlock support... yes
checking for pthread_rwlock support... yes
checking for sem_init in -lrt... yes
checking for semaphore support... yes

Checking for libxml2 support ...
checking for xml2-config... /usr/bin/xml2-config
checking libxml version... 2.9.10

Configuring for PCRE support ...
checking whether to compile with PCRE support... disabled

Configuring DocBook support ...
checking for jade... no
checking for openjade... no
checking for jadetex... no
checking for pdfjadetex... no
checking for dvips... no
checking for fig2dev... no
checking for convert... /usr/bin/convert
checking for /usr/lib/sgml/stylesheet/dsssl/docbook/nwalsh/html/docbook.dsl... no
checking for /usr/lib/sgml/stylesheets/nwalsh-modular/html/docbook.dsl... no
checking for /usr/share/sgml/docbook/dsssl-stylesheets-1.*/html/docbook.dsl... no
checking for /usr/share/sgml/docbook/dsssl-stylesheets/html/docbook.dsl... no
checking for /usr/share/sgml/docbook/stylesheet/dsssl/modular/html/docbook.dsl... no
checking for /usr/share/sgml/docbook/dsssl/modular/html/docbook.dsl... no
checking for /usr/share/sgml/dsssl/docbook-dsssl-nwalsh/html/docbook.dsl... no
checking for /usr/share/dsssl/docbook-dsssl/html/docbook.dsl... no
checking for /usr/local/lib/sgml/stylesheet/dsssl/docbook/nwalsh/html/docbook.dsl... no
checking for /usr/local/lib/sgml/stylesheets/nwalsh-modular/html/docbook.dsl... no
checking for /usr/local/share/sgml/docbook/dsssl-stylesheets-1.*/html/docbook.dsl... no
checking for /usr/local/share/sgml/docbook/dsssl-stylesheets/html/docbook.dsl... no
checking for /usr/local/share/sgml/docbook/stylesheet/dsssl/modular/html/docbook.dsl... no
checking for /usr/local/share/sgml/docbook/dsssl/modular/html/docbook.dsl... no
checking for /usr/local/share/sgml/dsssl/docbook-dsssl-nwalsh/html/docbook.dsl... no
checking for /usr/local/share/dsssl/docbook-dsssl/html/docbook.dsl... no
checking for /sw/lib/sgml/stylesheet/dsssl/docbook/nwalsh/html/docbook.dsl... no
checking for /sw/lib/sgml/stylesheets/nwalsh-modular/html/docbook.dsl... no
checking for /sw/share/sgml/docbook/dsssl-stylesheets-1.*/html/docbook.dsl... no
checking for /sw/share/sgml/docbook/dsssl-stylesheets/html/docbook.dsl... no
checking for /sw/share/sgml/docbook/stylesheet/dsssl/modular/html/docbook.dsl... no
checking for /sw/share/sgml/docbook/dsssl/modular/html/docbook.dsl... no
checking for /sw/share/sgml/dsssl/docbook-dsssl-nwalsh/html/docbook.dsl... no
checking for /sw/share/dsssl/docbook-dsssl/html/docbook.dsl... no
checking for /opt/local/lib/sgml/stylesheet/dsssl/docbook/nwalsh/html/docbook.dsl... no
checking for /opt/local/lib/sgml/stylesheets/nwalsh-modular/html/docbook.dsl... no
checking for /opt/local/share/sgml/docbook/dsssl-stylesheets-1.*/html/docbook.dsl... no
checking for /opt/local/share/sgml/docbook/dsssl-stylesheets/html/docbook.dsl... no
checking for /opt/local/share/sgml/docbook/stylesheet/dsssl/modular/html/docbook.dsl... no
checking for /opt/local/share/sgml/docbook/dsssl/modular/html/docbook.dsl... no
checking for /opt/local/share/sgml/dsssl/docbook-dsssl-nwalsh/html/docbook.dsl... no
checking for /opt/local/share/dsssl/docbook-dsssl/html/docbook.dsl... no
checking for /usr/lib/sgml/stylesheet/dsssl/docbook/nwalsh/print/docbook.dsl... no
checking for /usr/lib/sgml/stylesheets/nwalsh-modular/print/docbook.dsl... no
checking for /usr/share/sgml/docbook/dsssl-stylesheets-1.*/print/docbook.dsl... no
checking for /usr/share/sgml/docbook/dsssl-stylesheets/print/docbook.dsl... no
checking for /usr/share/sgml/docbook/stylesheet/dsssl/modular/print/docbook.dsl... no
checking for /usr/share/sgml/docbook/dsssl/modular/print/docbook.dsl... no
checking for /usr/share/sgml/dsssl/docbook-dsssl-nwalsh/print/docbook.dsl... no
checking for /usr/share/dsssl/docbook-dsssl/print/docbook.dsl... no
checking for /usr/local/lib/sgml/stylesheet/dsssl/docbook/nwalsh/print/docbook.dsl... no
checking for /usr/local/lib/sgml/stylesheets/nwalsh-modular/print/docbook.dsl... no
checking for /usr/local/share/sgml/docbook/dsssl-stylesheets-1.*/print/docbook.dsl... no
checking for /usr/local/share/sgml/docbook/dsssl-stylesheets/print/docbook.dsl... no
checking for /usr/local/share/sgml/docbook/stylesheet/dsssl/modular/print/docbook.dsl... no
checking for /usr/local/share/sgml/docbook/dsssl/modular/print/docbook.dsl... no
checking for /usr/local/share/sgml/dsssl/docbook-dsssl-nwalsh/print/docbook.dsl... no
checking for /usr/local/share/dsssl/docbook-dsssl/print/docbook.dsl... no
checking for /sw/lib/sgml/stylesheet/dsssl/docbook/nwalsh/print/docbook.dsl... no
checking for /sw/lib/sgml/stylesheets/nwalsh-modular/print/docbook.dsl... no
checking for /sw/share/sgml/docbook/dsssl-stylesheets-1.*/print/docbook.dsl... no
checking for /sw/share/sgml/docbook/dsssl-stylesheets/print/docbook.dsl... no
checking for /sw/share/sgml/docbook/stylesheet/dsssl/modular/print/docbook.dsl... no
checking for /sw/share/sgml/docbook/dsssl/modular/print/docbook.dsl... no
checking for /sw/share/sgml/dsssl/docbook-dsssl-nwalsh/print/docbook.dsl... no
checking for /sw/share/dsssl/docbook-dsssl/print/docbook.dsl... no
checking for /opt/local/lib/sgml/stylesheet/dsssl/docbook/nwalsh/print/docbook.dsl... no
checking for /opt/local/lib/sgml/stylesheets/nwalsh-modular/print/docbook.dsl... no
checking for /opt/local/share/sgml/docbook/dsssl-stylesheets-1.*/print/docbook.dsl... no
checking for /opt/local/share/sgml/docbook/dsssl-stylesheets/print/docbook.dsl... no
checking for /opt/local/share/sgml/docbook/stylesheet/dsssl/modular/print/docbook.dsl... no
checking for /opt/local/share/sgml/docbook/dsssl/modular/print/docbook.dsl... no
checking for /opt/local/share/sgml/dsssl/docbook-dsssl-nwalsh/print/docbook.dsl... no
checking for /opt/local/share/dsssl/docbook-dsssl/print/docbook.dsl... no
checking for /usr/lib/sgml/stylesheet/dsssl/docbook/nwalsh/dtds/decls/xml.dcl... no
checking for /usr/lib/sgml/stylesheets/nwalsh-modular/dtds/decls/xml.dcl... no
checking for /usr/share/sgml/docbook/dsssl-stylesheets-1.*/dtds/decls/xml.dcl... no
checking for /usr/share/sgml/docbook/dsssl-stylesheets/dtds/decls/xml.dcl... no
checking for /usr/share/sgml/docbook/stylesheet/dsssl/modular/dtds/decls/xml.dcl... no
checking for /usr/share/sgml/docbook/dsssl/modular/dtds/decls/xml.dcl... no
checking for /usr/share/sgml/declaration/xml.dcl... no
checking for /usr/share/sgml/dsssl/docbook-dsssl-nwalsh/dtds/decls/xml.dcl... no
checking for /usr/share/dsssl/docbook-dsssl/dtds/decls/xml.dcl... no
checking for /usr/local/lib/sgml/stylesheet/dsssl/docbook/nwalsh/dtds/decls/xml.dcl... no
checking for /usr/local/lib/sgml/stylesheets/nwalsh-modular/dtds/decls/xml.dcl... no
checking for /usr/local/share/sgml/docbook/dsssl-stylesheets-1.*/dtds/decls/xml.dcl... no
checking for /usr/local/share/sgml/docbook/dsssl-stylesheets/dtds/decls/xml.dcl... no
checking for /usr/local/share/sgml/docbook/stylesheet/dsssl/modular/dtds/decls/xml.dcl... no
checking for /usr/local/share/sgml/docbook/dsssl/modular/dtds/decls/xml.dcl... no
checking for /usr/local/share/sgml/declaration/xml.dcl... no
checking for /usr/local/share/sgml/dsssl/docbook-dsssl-nwalsh/dtds/decls/xml.dcl... no
checking for /usr/local/share/dsssl/docbook-dsssl/dtds/decls/xml.dcl... no
checking for /sw/lib/sgml/stylesheet/dsssl/docbook/nwalsh/dtds/decls/xml.dcl... no
checking for /sw/lib/sgml/stylesheets/nwalsh-modular/dtds/decls/xml.dcl... no
checking for /sw/share/sgml/docbook/dsssl-stylesheets-1.*/dtds/decls/xml.dcl... no
checking for /sw/share/sgml/docbook/dsssl-stylesheets/dtds/decls/xml.dcl... no
checking for /sw/share/sgml/docbook/stylesheet/dsssl/modular/dtds/decls/xml.dcl... no
checking for /sw/share/sgml/docbook/dsssl/modular/dtds/decls/xml.dcl... no
checking for /sw/share/sgml/declaration/xml.dcl... no
checking for /sw/share/sgml/dsssl/docbook-dsssl-nwalsh/dtds/decls/xml.dcl... no
checking for /sw/share/dsssl/docbook-dsssl/dtds/decls/xml.dcl... no
checking for /opt/local/lib/sgml/stylesheet/dsssl/docbook/nwalsh/dtds/decls/xml.dcl... no
checking for /opt/local/lib/sgml/stylesheets/nwalsh-modular/dtds/decls/xml.dcl... no
checking for /opt/local/share/sgml/docbook/dsssl-stylesheets-1.*/dtds/decls/xml.dcl... no
checking for /opt/local/share/sgml/docbook/dsssl-stylesheets/dtds/decls/xml.dcl... no
checking for /opt/local/share/sgml/docbook/stylesheet/dsssl/modular/dtds/decls/xml.dcl... no
checking for /opt/local/share/sgml/docbook/dsssl/modular/dtds/decls/xml.dcl... no
checking for /opt/local/share/sgml/declaration/xml.dcl... no
checking for /opt/local/share/sgml/dsssl/docbook-dsssl-nwalsh/dtds/decls/xml.dcl... no
checking for /opt/local/share/dsssl/docbook-dsssl/dtds/decls/xml.dcl... no
Not building documentation.

Configuring parameters ...
checking which malloc to use... native malloc
enabling local time
enabling cookies
enabling HTTP/1.1 keep-alive
checking whether to compile start-stop-daemon... enabled

Configuring OpenSSL support ...
checking whether to compile with SSL support... trying /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu /usr/include/openssl
checking for openssl... /usr/bin/openssl
checking openssl version... 1.1.0h
checking for HMAC_Update in -lcrypto... no

Configuring DB support ...
checking whether to compile with MySQL support... searching
checking for mysql_config... /usr/bin/mysql_config
checking mysql version... 5.7.29
checking mysql reentrant libs... -L/usr/lib/x86_64-linux-gnu -lmysqlclient -lpthread -lz -lm -lrt -lssl -lcrypto -ldl
checking for mysql_init in -lmysqlclient_r... no
checking mysql libs... -L/usr/lib/x86_64-linux-gnu -lmysqlclient -lpthread -lz -lm -lrt -lssl -lcrypto -ldl
checking for mysql_init in -lmysqlclient... no
configure: error: Unable to find MySQL client libraries
Fatal error occurred executing ./configure --prefix=/opt/ksmppd/build --with-mysql --enable-ssl --enable-start-stop-daemon --enable-static
-------------------------------------------------------------------------------------------------------------------------------------------------------------
Thanks in advance

**Comment by donald-jackson** [comment]
as you can see in the error message clearly it does not have the required MySQL libraries
