### ISSUE TITLE
TVL Prameter Issue

### ISSUE THREAD

**Issue by smppuser** [kneodev/ksmppd#134]
While trying to send the TVL parameters from my smpp user to ksmpp , Ksmpp not fetching the PE_id and Template_id.

This is my configuration file for ksmpp

group=ksmppd
id=****
log-file=/*****
log-level=4
smpp-port=****
database-type=mysql
database-config=*****
database-user-table=smpp_user
database-store-table=smpp_store
database-enable-queue=1
database-pdu-table=smpp_queued_pdu
database-route-table=smpp_route
inbound-queue-threads=4
outbound-queue-threads=4

group=mysql-connection
id=*****
host=localhost
username = *****
password = *****
database=new_smpp
max-connections=5

group=smpp-tlv
name=PE_ID
tag=0x1400
type=octetstring
length=20
smsc-id=****

group=smpp-tlv
name=Template_ID
tag=0x1401
type=octetstring
length=20
smsc-id=****

group=bearerbox-connection
id=****
id=****
host=localhost
port=****

group=http-server
port=****
password=****

group=smpp-routing
routing-method=1

Please let me know what i need to add in configuration for fetching TVL parameters by my ksmpp.

**Comment by veduyu** [comment]
Add the TLV Parameter to 
Bearerbox config it will work.
