### ISSUE TITLE
Unicode SMS Issue

### ISSUE THREAD

**Issue by voicecomms** [kneodev/ksmppd#136]
Hello, 

This is query rather than issue, when I am trying to send messages in Hindi it is going as blank messages and sometimes with junk characters I am using lightweight php smpp library with ksmppd and it is working like charm with normal sms, but when it comes to unicode I am doing utf-8 to ucs and then sending it (using coding type as 2) but then also getting the same issue any reference would be of great help.

Regards
CJ

**Comment by donald-jackson** [comment]
Please share your message and logs so we can check
