### ISSUE TITLE
SMS Getting rejected 

### ISSUE THREAD

**Issue by ChetanGJha** [kneodev/ksmppd#137]
Hello ,

I am using ksmppd and whenever i receive sms with + sign prefixed in front of number it is getting rejected, I know this is an configuration setting with dton and dnpi but should'nt ksmppd route all the messages with or without + ?

any help or insight would be appreciated.

Regards
Chetan

**Comment by donald-jackson** [comment]
Provide the error log please

**Comment by donald-jackson** [comment]
closed due to inactivity
