### ISSUE TITLE
log-level not honored?

### ISSUE THREAD

**Issue by docelic** [kneodev/ksmppd#141]
Hello,

Are there any issues with the log-level setting?

Changing it either via config file option `log-level` or via HTTP call `/log-level?level=` makes no effect.
The message printed appears affirmative, but the ksmppd's console keeps printing all the debug logs.

The log-level value I am trying to use is an int between 0 and 5.

Thanks

**Comment by donald-jackson** [comment]
No issues here, if you can provide further detail we can look into it.
