### ISSUE TITLE
how to send a DLR

### ISSUE THREAD

**Issue by mquevedob** [kneodev/ksmppd#142]
Is it possible to send a DLR back to the ESME ?

**Comment by mquevedob** [comment]
Hello guys! 

I have been checking but it seems like when a submit_sm comes from a ESME, no report_mo msg is stored for later DLR 

shouldnt a submit_sm trigger a smpp_database_add_message to store the report_sm ?

**Comment by donald-jackson** [comment]
no it uses the bearerbox to do this, the return routing is encoded in the dlr-url
