### ISSUE TITLE
ksmppd upgrade dlr-proxy-err-long' directive

### ISSUE THREAD

**Issue by bharat-ux** [kneodev/ksmppd#147]
What will happen in it that the error code that ksmppd will receive will be of 6 digits, which will make it easy for the client to answer what the error is due to.

**Comment by harshpareek** [comment]
@donald-jackson Please update on this, how we increase length or error code from 3 to 4 or more

**Comment by donald-jackson** [comment]
Hi there, KSMPPD doesn't have its own code to generate and parse SMPP PDUs, it uses Kannel's libraries - so if you want fundamental changes like that you will need to raise them on the Kannel developer forum. I'm almost certain they will decline your request though as this breaks the SMPP specification.
