### ISSUE TITLE
amqpbox

### ISSUE THREAD

**Issue by bharat-ux** [kneodev/ksmppd#149]
Whenever you upgrade ksmppd use amqpbox (rabbitmq ) instead of sqlbox
This will allow us to take MT in large volume

**Comment by donald-jackson** [comment]
You can use any of the box services with ksmppd (bearerbox, sqlbox, pluginbox, etc), just configure it as you desire.

**Comment by tiltroom** [comment]
Hey @donald-jackson sorry for reopening this but would you kindly provide more details about this? Looking at the examples and wiki it is not quite clear how to make KSMPPD and sqlbox fit together.
Thanks
