### ISSUE TITLE
Sending messages back to esme

### ISSUE THREAD

**Issue by docelic** [kneodev/ksmppd#151]
Hey,

I am testing ksmppd and sending messages from esme to smsc works fine.

But I don't understand how to send messages from smsc back to esme.
I thought there would be a HTTP endpoint exposed, through which I could submit a message to be delivered back to esme.
But so far I didn't identify that endpoint nor some other way to do it.

Could you provide some pointers? Thanks!

**Comment by docelic** [comment]
Any hints/comments maybe? Thanks.

**Comment by donald-jackson** [comment]
These come from your upstream esme or bearerbox, so to send MO messages they need to be injected into bearerbox or your upstream gateway
