### ISSUE TITLE
ksmppd get crashed when only Tx bind is conneced 

### ISSUE THREAD

**Issue by freesmppforu** [kneodev/ksmppd#20]
when i connect only Tx session and pushed sms through the esme Tx bind. ksmppd get crashed after sometime when simulation is turned on

**Comment by kneodev** [comment]
Please provide more detail, I can't help you without any information.

**Comment by freesmppforu** [comment]
try this scenario

create an esme with 3 binds and enable the simulation mode with delivered every 3 and permanent failed every 5 and connect all bind as Tx sessions and push sms through this esme user after pushing 100 sms or more ksmppd get crashed
