### ISSUE TITLE
KSMPP ID is not submitting in SQLBOX

### ISSUE THREAD

**Issue by thesanthosh** [kneodev/ksmppd#22]
Hi,

When we submit sms the message id is not submitted to the sqlbox.

**Comment by kneodev** [comment]
This is not possible. Messages cannot transmit without an ID

**Comment by thesanthosh** [comment]
i have used all http api authentication neo.
only acknowledgment i given in smpp-route.php is smscid and i got the message.
where in the sent table of sqlbox iam able to see the ID field as null ?

**Comment by kneodev** [comment]
I'm sorry, I don't know your personal setup but if you are seeing null ids in your database you are making a mistake somewhere. Check all your configuration and code again.

**Comment by thesanthosh** [comment]
i found the problem neo.

thanks.

in smpp-route.php it mention as 'X-Ksmppd-Id' => '7a9a1271-7ed4-4c6f-af6f-8652252010ab'


but actually it is 'X-Ksmppd-id' => '7a9a1271-7ed4-4c6f-af6f-8652252010ab'

Thank you.

**Comment by kneodev** [comment]
HTTP headers should be treated as case insensitive as per the RFC, just check your system implementation.
