### ISSUE TITLE
X-Ksmppd-Msgdata Unicode Data not correct

### ISSUE THREAD

**Issue by thesanthosh** [kneodev/ksmppd#24]
Hi neo,

iam testing the only http options.

where when i receive unicode messages the messages are coming in some encoded format which we are not able to decode.

Unicode Billing cant be possible without this data coming in.

**Comment by kneodev** [comment]
Data is URL encoded, you will need to decode first. See examples

**Comment by thesanthosh** [comment]
Hi neo,
 actual message submitted in smpp : ടെസ്റ്റ് സംസ്‌ 

after url decode : F8M1M1M 88M 

This the problem.

**Comment by kneodev** [comment]
Please provide the raw HTTP headers so I can see (the headers not decoded)

eg %20%2B etc

**Comment by thesanthosh** [comment]
%0D%1F%0DF%0D8%0DM%0D1%0DM%0D1%0DM%00+%0D8%0D%02%0D8%0DM+%0C

**Comment by kneodev** [comment]
I can decode this fine?

```
<?php
$raw = "%0D%1F%0DF%0D8%0DM%0D1%0DM%0D1%0DM%00+%0D8%0D%02%0D8%0DM+%0C";
$data = iconv("UTF-16BE", "UTF-8", urldecode($raw));

print($data);
print("\n");
```
Output

```
php decode.php
ടെസ്റ്റ് സംസ്‌
```
