### ISSUE TITLE
custom dlr

### ISSUE THREAD

**Issue by thesanthosh** [kneodev/ksmppd#25]
when decision of rejecting the message at http api - smpp-route.php 

we are able to reject only with 45 error nack (SUBMIT FAILED)

how to Reject with Custom errors on http api without passing to smsc.

**Comment by thesanthosh** [comment]
Hi neo thanks for the update.
i was testing the same like this,

Header('X-KSMPPD-Route-Error-Code: SMPP_ESME_RBINDFAIL');

but still NACK/0X00000045/SUBMIT FAILED is coming as default.

**Comment by kneodev** [comment]
@thesanthosh you need to use the decimal integer values SMPP_ESME_RINVDLNAME = 54

**Comment by thesanthosh** [comment]
neo actually tried that but it is coming as NACK/0X00000036/UNKNOWN/RESERVED

**Comment by kneodev** [comment]
@thesanthosh that is the correct code, your client is not handling it appears

**Comment by thesanthosh** [comment]
Hi neo,
kindly help me tried all way around.
when datasubmit is coming to http page i have placed the 
Header('X-KSMPPD-Route-Error-Code: 54');

but still getting error:NACK/0X00000036/UNKNOWN/RESERVED
