### ISSUE TITLE
source_regex inquiries

### ISSUE THREAD

**Issue by lamnt2012** [kneodev/ksmppd#26]
Hello Kurt,
I have some issues with source regex for special sender:
- Brandname sender which contains under square '_' character, e.g ^(GOOGLE_NOW)$ is not work
- ^(123\d\d)$ is not work, such as want to limit sender from 12300 to 12399.
And if source regex is not matched, ksmppd box responds "0x0000000b/Invalid Destination Address", it should be "Invalid Source Address", isn't it?

Many thanks.
Lamnt.
.

**Comment by kneodev** [comment]
Error code has been patched.

Please make sure you are using POSIX compatible regular expressions, like

^(123[0-9][0-9])$ works 

GOOGLE_NOW regular expression works as is, what error code are you getting? Please share logs.

**Comment by lamnt2012** [comment]
Thanks alot Kurt,
^(123[0-9][0-9])$ works
GOOGLE_NOW works also now as i have removed alt-charset = "ASCII" in my smsc configuration.
Please close the case.

**Comment by kneodev** [comment]
Thanks @lamnt2012 I can see why you had a problem with _ if you were using ASCII as this would be converted incorrectly. KSMPPD default character set is GSM 7bit

**Comment by hadpro24** [comment]
> ASCII

I need to add alt-charset="ISO-8859-1" or kannel doesn't encodes my messages correctly. ... How can I config that if I need add "ISO-8859-1"
