### ISSUE TITLE
Issue With installing Ksmppd

### ISSUE THREAD

**Issue by coinhosting** [kneodev/ksmppd#30]
Hi,

i have tried to install ksmppd on centos_6_64x on vps server but during run command "./bootstrap.sh" i receive error below 

/usr/bin/svn: error while loading shared libraries: libaprutil-1.so.0: cannot open shared object file: No such file or directory
Fatal error occurred executing /usr/bin/svn checkout -r 5173 https://svn.kannel.org/gateway/trunk kannel-svn-trunk

please help 

Thanks 
Deepak

**Comment by kneodev** [comment]
Looks like your subversion doesn't work, this isn't an issue with ksmppd

Run the command svn and if it doesn't work fix that first, then try again
