### ISSUE TITLE
how to connect ksmppd with sqlbox

### ISSUE THREAD

**Issue by coinhosting** [kneodev/ksmppd#31]
hi,

how to connect ksmppd with sqlbox or how to manage reports over smpp please guide am unable to find anything in readme file regarding this 

thanks

**Comment by lamnt2012** [comment]
Suppose your approach shoule be: bearerbox (13001) ---- sqlbox (13005) ----- ksmppdbox (14000)

So just configure your ksmppbox like this:

group=bearerbox-connection
id=KSMPPD
host=localhost
port=13005 # sqlbox's port

**Comment by coinhosting** [comment]
Thanks it's working now,

please let me know if their any option to active / inactive an account (user)

thanks

**Comment by coinhosting** [comment]
And please tell which encryption using to create password ?

**Comment by kneodev** [comment]
@coinhosting use MySQL built in PASSWORD() function for hashing

**Comment by riteshraor2k** [comment]
hi

I just wanted to know , if we put sqlbox in between  ksmppbox and bearerbox , how to trap the value of credit deducted of per sms in sentsms table ?
if anybody helps , that wili be great for us
