### ISSUE TITLE
How to use fake sms with ksmppd and how to have mode tutorial

### ISSUE THREAD

**Issue by Roll72** [kneodev/ksmppd#32]
Hello,

I succeeded installing ksmppd and kannel, and would like to know if it is possible to use the tool fakesms of kannel to make test on my platform ?

By the way, is it possible to have moe tutorial ? how to contibute ?

thanks in advance for your support

**Comment by kneodev** [comment]
Yes you can use fake smsc as with Kannel. Just configure it to route appropriately to your KSMPPD
