### ISSUE TITLE
How to use Routes

### ISSUE THREAD

**Issue by coinhosting** [kneodev/ksmppd#33]
Hi,

 i have installed ksmppd and its works fine but am unable to use database based routing i mean ( if i set default_smsc in user table so it's don't match routing rules and if i keep this filed blank or null is reply "NACK%2F0x0000000b%2FInvalid+Destination+Address") 

kindly suggest how i can use routing also how i can change bind mode for an user (TX, RX or TRX)

Thanks

**Comment by kneodev** [comment]
Please provide logs and database snapshot
