### ISSUE TITLE
error

### ISSUE THREAD

**Issue by coinhosting** [kneodev/ksmppd#34]
Hi,

i have install and configure ksmppd and it's work perfectly all sms deliver and reports everything works fine 

but in ksmppd logs i can see 1 error which i receive continuously 

[15] ERROR: SMPP: Unknown TLV `dlr_err', don't send.

can anyone help me to resolve this error 

thanks

**Comment by coinhosting** [comment]
and also please let me know what does means simulate_mo_every, failure, delivery etc

**Comment by kneodev** [comment]
@coinhosting please read documentation https://github.com/kneodev/ksmppd/wiki/MySQL:-smpp_user-column-meanings

You can ignore that error, its just an unconfigured optional parameter
