### ISSUE TITLE
issue with long sms

### ISSUE THREAD

**Issue by coinhosting** [kneodev/ksmppd#35]
Hi,

i have configure ksmppd with kannel and sqlbox all functions works fine but i have little issue with long sms dlr incase of long sms(more then 160 char) i receive first sms dlr and once my provided send second sms dlr it's showing error in logs

got DLR but could not find message or was not interested in it id<xxxxxxxxx> dst<9876543210>, type<1>

am using smpp for as smsc 

please anyone help me to resolve this issue

**Comment by kneodev** [comment]
This is a Kannel error message, please do not raise issues here for bearerbox/sqlbox problems

**Comment by coinhosting** [comment]
Hi,

thanks for your update 

but i think issue with ksmppd because it's send dlr-mask 0 with every extra part of long sms if it's send dlr-mask 19 for every part i surely receive dlr for every part 

can you please help me to configure ksmppd to send dlr mask 19 for every message part

thanks

**Comment by kneodev** [comment]
Incorrect. ksmppd doesn't deal with concatenated mangling. You are confusing ksmppd with kannel bearerbox
