### ISSUE TITLE
issue with dlr-mask

### ISSUE THREAD

**Issue by coinhosting** [kneodev/ksmppd#36]
Hi,

as per my last question i have issue with long sms please check few points which i notice

i think issue with ksmppd because it's send dlr-mask 0 with every extra part of long sms if it's send dlr-mask 19 for every part i surely receive dlr for every part

can you please help me to configure ksmppd to send dlr mask 19 for every message part

thanks

**Comment by kneodev** [comment]
Please stop spamming issues here, this is not a ksmppd problem. Please mail Kannel users group for help

**Comment by india-india** [comment]
hello sir 
iam using ksmppd , and iam doing authentication + routing via database , every this is working but iam unable to set the dlr_url param and dlr-mask , kindly please tell me how i can do this things.


thanks in Advance sir .
