### ISSUE TITLE
Long sms handling

### ISSUE THREAD

**Issue by Capricorn00** [kneodev/ksmppd#37]
Hi,

i'm testing kannel to kannel connection, my test configuration:

[playsms1 -> smsbox1 -> sqlbox1 -> kannel1] ---> [opensmppbox3 -> sqlbox3 -> kannel3] ---> [ksmppd2 -> sqlbox2 -> kannel2] ---> [SMSC]

I send long sms from playsms1, it is stored in sqlbox1 as one part (one record with dlr-mask 31). 
Received by opensmppbox in sqlbox3, it is still stored as one part (one record with dlr-mask 19).
Received by ksmppd in sqlbox2, it is stored as three parts (three records one with dlr-mask 19 and two with 0).
Is it posible to configure ksmppd to concatenate sms as opensmppbox do ?.
Other question is it posible to change(set) default dlr-mask from 19 to 31 for sms received by ksmppd(or opensmppbox)?

Regards.

**Comment by kneodev** [comment]
I don't see any benefit in assembling the messages like opensmppbox does given the target users of ksmppd.

The dlr mask you are seeing is being set by kannel bearerbox, it only sets dlr mask for the first part of the message.

**Comment by Capricorn00** [comment]
How to select all parts msg (msgdata) from sqlbox (dlr_url is different for all parts) ?

**Comment by kneodev** [comment]
Use the udh data to reassemble if needed

**Comment by Capricorn00** [comment]
Thanks
