### ISSUE TITLE
DLR not available anywhere

### ISSUE THREAD

**Issue by sherifkozman** [kneodev/ksmppd#41]
Currently we have deployed KSMPPD with SQLBOX & Kannel 1.4.4
Everything seems to be working fine in testing phase and able to submit outbound messages from ESME >> KSMPPD >> SQLBOX >> KANNEL

However i have noticed that all dlr_mask values are set to 19 and also we have no idea how to track DLR or view the status?

Another note is keeping track of the original ESME Message ID Vs the SMSC or Kannel Msg ID

**Comment by kneodev** [comment]
If you are using kannel memory storage I'm not sure there is a way to track them. If you are using database for dlr you can use the database table, but they get deleted once processed.

I'm not familiar with sqlbox internals but I'm sure it would store dlr's somewhere.

ksmppd embeds its dlr data in the dlr url which is returned by bearerbox to match to original ESME so no outside storage

**Comment by sherifkozman** [comment]
I am using Kannel MySQL storage as well as SQLBox MySQL so i can be able to compare and track all hits. However for KSMPPD, i can't find find any of the tables holding a DLR value anywhere, it might be routed back to the ESME but can't find any trace of it in the database.

**Comment by kneodev** [comment]
ksmppd doesn't store dlr's in database unless they get queued for an ESME which isn't currently online. I don't think you are looking in the right place for what you need
