### ISSUE TITLE
DND Filtration

### ISSUE THREAD

**Issue by Robinc01** [kneodev/ksmppd#42]
Hi,

Is it possible to filter dnd numbers send by the smpp users.?

**Comment by kneodev** [comment]
I think @donald-jackson was working on a patch like this

**Comment by Robinc01** [comment]
No. He said he is not working on it.

**Comment by wasimbaig** [comment]
i would think that using a http router for any 'user-space logic' like this or blacklist, DND, sender override, dlr force etc is the way to go

**Comment by ib1corp** [comment]
Hi, we were struggling with kannel and the open source smpp servers all these years.

Finally we have developed our own In-house SMPP Server fully built on node.js & nosql technology. It has a capacity of validating DND Numbers/Blacklist/Spam/Intelligent Routing/SenderId based routing etc and a benchmark tested validation speed of 25+ Lakh message validations per second. SMPP TPS is scale-able to several thousand TPS. If anyone is interested in enterprise grade smpp server with the ability to shed a high budget/price, please contact me "iwebpush" at gmail dot com

**Comment by donald-jackson** [comment]
@Roll72 yes - https://github.com/kneodev/ksmppd/blob/master/example-configurations/http-only/php-example/smpp-route.php

regarding user space implementation, agree with @wasimbaig this should be implemented as a plugin.

**Comment by ib1corp** [comment]
Hi @Roll72 , we have developed an API for use with ksmppd http routing, using redis as the db, it does DND Filtering, Spam Filtering, Blacklist Filtering, Sender/CLi filtering . REDIS (uses RAM) for data storage and validation. The coding is such that DND Data of over 50 Crore+ numbers can be stored in less than 512mb of RAM. The processing speed is excellent. If you need any help you can contact me. "iwebpush" '@' gmail dot com

PS: thanks to @kneodev & @donald-jackson for such a wonderful application.

**Comment by donald-jackson** [comment]
@ib1corp please do not spam this project with commercial messages or you will be banned.
