### ISSUE TITLE
custom dlr

### ISSUE THREAD

**Issue by thesanthosh** [kneodev/ksmppd#46]
Hi neo,
kindly help me tried all way around.
when datasubmit is coming to http page i have placed the
Header('X-KSMPPD-Route-Error-Code: 54');

but still getting error:NACK/0X00000036/UNKNOWN/RESERVED

======

and one more query explaining an assumption:

esme client connected to the smpp server and we have again connected to an operator account.

a message submitted by esme user goes to operator and operator gives back dlr resp sometimes with txt ref and some custom data basically varies from operator to operator.

while at our smppserver how to customise those values dynamically or via a db storage.

this is a big problem in the smppserver as you are forced to send responses sent by operators and everytime you change your operator to another the error reasons and mapping changes again.
where we wanted to maintain static error codes so esme user need not to worry of updating error codes every time operator changes in use cases.

**Comment by kneodev** [comment]
it looks like your client is not dealing with the error codes, it doesn't look like a problem with ksmppd as it is correctly sending the 0x36 error code when you send decimal 54

**Comment by thesanthosh** [comment]
How to send the UNKNOWN/RESERVED space with valid text response in return to the error codes?

**Comment by kneodev** [comment]
@thesanthosh i think this is where you are not understanding. That 'UNKNOWN/RESERVED' text is what your client is showing. SMPP only has error code numbers, no text.
