### ISSUE TITLE
HTTP server esme-unbind respond wrong system ID which is not exist

### ISSUE THREAD

**Issue by nmtbk** [kneodev/ksmppd#5]
http://localhost:14010/esme-unbind?password=ksmppdpass&system-id=dummy
**No such system-id '08' found**
It responds "08" or some junks instead of "dummy"

**Comment by kneodev** [comment]
Please provide output of the status page when (esme-status) before you get this error

**Comment by nmtbk** [comment]
**http://localhost:14010/esme-status?password=ksmppdpass**
_Summary:_ 

_Unique known ESME's: 1_
_Total inbound processed:3 load: 0.00/0.00/0.00/sec_
_Total outbound processed:0 load: 0.00/0.00/0.00/sec_

_myid - binds:1/0, total inbound load:(0.00/0.00/0.00)/11.00/sec, outbound load:(0.00/0.00/0.00)/sec
-- id:0 uptime:0d 0h 38m 30s, type:3, open-acks:0, inboun_d _(load/queued/processed/routing):0.00/0/17/0, outbound (load/queued/processed):0.00/0/17_

**http://localhost:14010/esme-unbind?password=123&system-id=dummy**
_No such system-id 'P' found_

**http://localhost:14010/esme-unbind?password=123&system-id=myid**
_1 binds disconnected_

**Comment by kneodev** [comment]
Fixed via 2b33887208f708f1ffb556f44c53b14f8c9ac138
