### ISSUE TITLE
Error converting from GSM to Unicode

### ISSUE THREAD

**Issue by dspasoski** [kneodev/ksmppd#50]
Hi,

I come across the following or similar entries in the ksmppd log:
2017-04-12 19:13:05 [28754] [9] WARNING: Could not convert GSM (0xfc) to Unicode.

It is u with umlaut character (ü) (Latin-1/ISO-8859-1 maybe) and it's hex code is clearly outside of the GSM alphabet. It implies client is not using 7-bit GSM.
I expect that ksmppd must convert everything to utf-8 before passing to bearerbox, but question is when DCS=0, ksmppd doesn't know which default alphabet the client is using. Most frequently it is one of ISO-8859-1, ASCII or GSM.
What is the conversion policy of ksmppd? Will it reject the entire SMS or replace the sign with "?".
Please consider adding default alphabet setting for the client so that the conversion to utf-8 is proper.

Davor

**Comment by kneodev** [comment]
ksmppd treats data_coding = 0x00 as GSM character set same as Kannel

I will consider adding alt-charset support for ESME connections

**Comment by dspasoski** [comment]
Great. Looking forward.

**Comment by dspasoski** [comment]
Hi,
Any plans for this enhancement?
Davor

**Comment by Roll72** [comment]
you can make a post-billing using DCS, if Data coding = 8 in the SMPP then it will be Unicode, and max caracteres in sms will be about 70.

**Comment by donald-jackson** [comment]
fixed in ef7d80fba2d496d3c17829cd77ecdfd265ad7c31
