### ISSUE TITLE
Question: Enquire link policy

### ISSUE THREAD

**Issue by dspasoski** [kneodev/ksmppd#51]
Hi,

What is the enquire_link policy (frequency, who is expected to initiate first, etc)?

Davor

**Comment by kneodev** [comment]
ksmppd policy for enquire links is to send an enquire link if no traffic (any valid PDU type) has been received on the link for 180 seconds. There is no expection from ksmppd for an ESME to initiate an enquire link but the ESME can do so if they choose.

**Comment by dspasoski** [comment]
Thanks. That's what my tests confirmed. The problem is with the client unbinding and binding for each and every SMS and that results in the issue #49 
I'm closing this one and focusing on #49
