### ISSUE TITLE
Message_id too long for SMPP 3.3 clients

### ISSUE THREAD

**Issue by dspasoski** [kneodev/ksmppd#56]
Hi,
This issue is related to issue #49 but the source of the problem deserves separate issue id.
Namely, #49 describes a problem related to two clients that were disconnecting all the time.
I isolated one of the clients that is disconnecting after each and every message on opensmppbox and the problem was not evident. A short comparison of the tcpdumps below reveals that opensmppd sends shorter message_id in the submit_sm_response PDU, while ksmppd is using very long message ids:
[https://www.dropbox.com/s/nqfwx14by3e121r/smpp33_on_ksmppd.pcap?dl=0](https://www.dropbox.com/s/nqfwx14by3e121r/smpp33_on_ksmppd.pcap?dl=0)
[https://www.dropbox.com/s/p8yxew5atmekkc8/smpp33_on_opensmppbox.pcap?dl=0](https://www.dropbox.com/s/p8yxew5atmekkc8/smpp33_on_opensmppbox.pcap?dl=0)
Differences in SMPP 3.3 and SMPP 3.4 [standards](https://en.wikipedia.org/wiki/Short_Message_Peer-to-Peer#Incompatibility_of_submit_sm_resp_between_SMPP_versions) mention that in SMPP3.3 message_id ia null terminated C-octet (HEX) stream with up to 8 characters (plus the null), while in SMPP3.4 this was 9, 33 and then 63 characters.
The ESME is sending 0x00, which according to the [standard](https://support.nowsms.com/discus/messages/1/SMPP_v3_4_Issue1_2-24857.pdf) (page 46) indicates properly version 3.3 or earlier.

**Comment by kneodev** [comment]
ksmppd only supports smpp v3.4 and above.

smpp 3.4 was issued in 1999, 18 years should be enough to have moved.
