### ISSUE TITLE
SMPP password length issue

### ISSUE THREAD

**Issue by nmtbk** [kneodev/ksmppd#58]
Seem kannel only support SMPP password up to 8 characters. In case of creating an SMPP account for clientA on KSMPPD box which have password's length > 8 characters, kannel automatically truncate the password into 8 while submit the bind to KSMPPD but there is no response at all from KSMPPD.

Here is ksmppd log:
2017-05-28 22:32:27 [15284] [4] WARNING: SMPP[clientA] Has no receivers connected, queuing in database

**Comment by kneodev** [comment]
SMPP specification only allows for up to 8 characters in password length
