### ISSUE TITLE
not able to track long messages with a common ID to update DLR

### ISSUE THREAD

**Issue by thesanthosh** [kneodev/ksmppd#59]
Hi Neo,
we are not able to track or update the DLR for the below-given scenario,

ESME user submit's 300 character message which is two part messages,
we are able to receive it via ksmppd and update it to our DB like,
eg values: message ID 1000 with part 1 message this is row1,
message id 1001 with part 2 message and this is row2 in DB Note there is no similarity is message id given by smpp as well, so they are considered as two different messages.
and process them to the end Destined SMSC,

The Problem,

While the SMSC is taking this that is reaching operator and delivery happened.
while end vendor replies back with 1 DLR report with 1st part msg id with DLR response,
and we are updating part1 msg with Delivered,

while the part2 doesn't get delivery reports from the vendor as this is one long message.

Request you to make me understand how to sort this scenario as am confused how to solve this matter.

Thanks.

**Comment by dspasoski** [comment]
Hi,

Sorry I’m popping-in in the conversation. Maybe this thread explains why this is so:

http://www.kannel.org/pipermail/users/2016-February/022663.html

Davor Spasoski

**Comment by thesanthosh** [comment]
Hi thanks for updates though.
i made bug fix at my kannel to do the needful.
thank you.

**Comment by veduyu** [comment]
@thesanthosh I have the same issue can you tell me how you fix that..

**Comment by hiteshkar** [comment]
Dear santhosh
Kindly share the info how to fix that bug.
Getting first part dlr only rest part is unknown.
My email-id : hiteshkar2008@gmail.com
