### ISSUE TITLE
Throttling error for long SMS

### ISSUE THREAD

**Issue by nmtbk** [kneodev/ksmppd#6]
When submit only a long SMS (>160 characters) to KSMPPD, got the throttling error in ksmppd log as below. The 1st sms segment is delivered to smsc and the remains are queued then sent later one by one:
2016-08-20 17:31:03 [1646] [11] ERROR: SMPP[test] Exceeded throughput 45.189450, 11.000000, throttling.
2016-08-20 17:31:03 [1646] [16] DEBUG: SMPP[test:0] Got outbound queued PDU (1) seq 0:

**Comment by kneodev** [comment]
This is not an error, your client is sending faster than the allowed throughput of 11 that you have configured.

**Comment by nmtbk** [comment]
Sorry Kneo, as i wrote, i only submit **01 long sms** (exactly 161 characters) from the client. It is definitely an issue.

**Comment by kneodev** [comment]
Please feel free to submit a pull request with your proposed fixes or changes to improve this. Currently behaviour is using standard Kannel load.[c|h] internals.

**Comment by nmtbk** [comment]
Thanks Kurt, i found the issue from my client configuration that throughput is setting higher than 11 TPS. So even i submitted only 1 long SMS, the KSMPPD still generate above error.

**Comment by kneodev** [comment]
What version of Kannel are you using?

-- 
Kurt

**Comment by nmtbk** [comment]
After your previous advise, i've updated both client and service side to Kannel bearerbox version `svn-r5172' then change the throughput in client smpp configuration. If set > 11 TPS, i still get that error for long sms.

**Comment by kneodev** [comment]
If your client throughput is higher than 11 and you have the ksmppd limit
of 11 in the database you will get the error. This is the correct behavior.

-- 
Kurt

**Comment by nmtbk** [comment]
Yes, i understand the concept. Just wonder that i submitted nothing but a long sms 2 segments so the throughput should < 2 TPS regardless what i set in client smpp configuration throughput. Whatever, i had configured it <= 11 and no error log any more. Thank you for your time. Have nice weekend.
