### ISSUE TITLE
How ksmppd propagates source and destination TON/NPI when submitting to bearerbox

### ISSUE THREAD

**Issue by dspasoski** [kneodev/ksmppd#65]
Hi,

I wonder how ksmppd treats the original values that the SMPP client has set for submit_sm? I notice that whatever I set for destination TON/NPI, with the exception of 5/0 it's being sent to SMSC with TON/NPI=2/1

For anything else but a destination in international format, it doesn't matter, but I'm practically unable to send a properly formatted destination number with TON/NPI = 1/1. Instead it is necessary to actually add a + prefix and pack that in other TPN/NPI values. I'm trying to nail which is changing the values ksmppd or bearerbox?

**Comment by dspasoski** [comment]
P.S. 
Since the combination of ksmppd and bearerbox is a sort of an SMPP proxy and not an HTTP to SMPP gateway, I believe it should be possible the clients' TON/NPI to pass through unmodified. Maybe a configuration line for submit_sm like "let-original-ton-npi = yes"

**Comment by kneodev** [comment]
ton/npi is a smpp specific thing where kannel is smpp agnostic. Ton/npi doesn't exist in any kannel structure other than the smpp configurations, so it is always passed as received by ksmppd
