### ISSUE TITLE
Additional feature for outbound message routing

### ISSUE THREAD

**Issue by nmtbk** [kneodev/ksmppd#7]
From comments in sample routing tables, i understand that Kneo intents to route defined origination short codes (such as ^(1800)) to respective smsc_id submitted by each system_id. But in fact, the regex is applied for destination numbers. Seem Kneo treats this exactly similar to inbound message (MO) concept. 
Since in actual use cases for outbound msg, we need rule for origination number rather than destination number. Thanks.

**Comment by nmtbk** [comment]
Hello Kneodev,
Seeing you are doing well. May i ask do you have any plan to enhance this feature? I love to use this box but impossible because without the rule, client can even fake the sender to anything they want.
Thank you.

**Comment by kneodev** [comment]
Wiki updated with source_regex parameter explanation. 

https://github.com/kneodev/ksmppd/wiki/MySQL:-smpp_route-column-meanings
