### ISSUE TITLE
Excluding in process number 1 (last one = 10)

### ISSUE THREAD

**Issue by Roll72** [kneodev/ksmppd#75]
Hello,
I have the following configuration : Bearerbox-sqlbox-Ksmppbox.
I'm trying to test the following scenario : one SMPP client send a sms (dlr=19), but disconnected just after, then the sms is received and ksmpp store the DLR in the SMPP_STORE table. When the SMPP "client" reconnect to the ksmpp, the ksmpp is suppose to give back the dlr(=1) to the originator. 
I have the following error message (many time) in ksmpp log : 
2018-02-13 10:46:41 [2519] [17] INFO: Excluding in process number 1 (last one = 10)
But no DLR coming in the SMPP client side (which is also a kannel).
Does someone have any idea about this issue ?

thanks in advance

**Comment by Roll72** [comment]
I forgot to mention this in the log : 
2018-02-13 11:37:04 [2519] [9] INFO: Got db msg queue callback for 11 status 100
2018-02-13 11:37:04 [2519] [9] ERROR: SMPP: Unknown TLV `dlr_err', don't send.
2018-02-13 11:37:04 [2519] [17] INFO: Excluding in process number 1 (last one = 11)

**Comment by ib1corp** [comment]
Hi @Roll72, the original developer @kneodev is missing since a year now. this project is no longer being updated or supported by anyone (unfortunately).

**Comment by Roll72** [comment]
Hello,

 

I can support it but I need time and this time is not easy to find, I have to work to eat!

 

De : ib1corp [mailto:notifications@github.com] 
Envoyé : mercredi 16 mai 2018 09:00
À : kneodev/ksmppd
Cc : Roll72; Mention
Objet : Re: [kneodev/ksmppd] Excluding in process number 1 (last one = 10) (#75)

 

Hi @Roll72 <https://github.com/Roll72> , the original developer @kneodev <https://github.com/kneodev>  is missing since a year now. this project is no longer being updated or supported by anyone (unfortunately).

**Comment by Roll72** [comment]
I find out my issue by myself, so the thread is closed

 

De : ib1corp [mailto:notifications@github.com] 
Envoyé : mercredi 16 mai 2018 09:00
À : kneodev/ksmppd
Cc : Roll72; Mention
Objet : Re: [kneodev/ksmppd] Excluding in process number 1 (last one = 10) (#75)

 

Hi @Roll72 <https://github.com/Roll72> , the original developer @kneodev <https://github.com/kneodev>  is missing since a year now. this project is no longer being updated or supported by anyone (unfortunately).

**Comment by kneodev** [comment]
thanks, please comment your solution
