### ISSUE TITLE
ksmpp and accss log

### ISSUE THREAD

**Issue by riteshraor2k** [kneodev/ksmppd#78]
i just wanted to know , where the logs of submit-sm and deliver_sm are stored ?
which we can show to clients for reference ?

**Comment by Roll72** [comment]
They are in the database. It should be like a table named 'smpp_store' if you stayed with the default name

**Comment by Roll72** [comment]
oh, sorry, 'smpp_store' handled the dlr and log when esme is not available. But if you configure sqlbox, you should have all the needed information in sent_sms table

**Comment by riteshraor2k** [comment]
Hi thanks for the info .
i put sqlbox in between , but i dont see credit deduction rate per sms which we pass at pluginlevel .
can you please help us how to get that value ?

**Comment by Roll72** [comment]
to have credit deduction you should have the good information in smpp_user. At least one user must have  enable_prepaid_billing=1 and default_cost=1 and some credit !

**Comment by riteshraor2k** [comment]
below is the sent_sms table , which column will show the credit deduction ?
also  below is my ksmpp user table data from my demo setup ,
ii dont seee any credit per sms  information in sent_sms table .


+-----------+-------------------------------------------+------------+--------------+--------------+------------------------+-------------------+--------------+----------+------------------------+----------------------------------+----------------------------------+-------------------+-----------+------------------+
| system_id | password                                  | throughput | default_smsc | default_cost | enable_prepaid_billing | credit            | callback_url | simulate | simulate_deliver_every | simulate_permanent_failure_every | simulate_temporary_failure_every | simulate_mo_every | max_binds | connect_allow_ip |
+-----------+-------------------------------------------+------------+--------------+--------------+------------------------+-------------------+--------------+----------+------------------------+----------------------------------+----------------------------------+-------------------+-----------+------------------+
| smppusera | *94BDCEBE19083CE2A1F959FD02F964C7AF4CFC29 |   11.00000 | smpp_g01     |       0.0005 |                      1 | 999.9989000000003 | NULL         |        0 |                      0 |                                0 |                                0 |                 0 |         0 | NULL             |
| smppuserb | *94BDCEBE19083CE2A1F959FD02F964C7AF4CFC29 |    0.00000 | smpp_g01     |       0.0005 |                      0 |              1000 | NULL         |        1 |                      1 |                                0 |                                0 |                 0 |         2 | NULL             |
| smppuserc | *94BDCEBE19083CE2A1F959FD02F964C7AF4CFC29 |    0.00000 | smpp_g01     |       0.0005 |                      0 |              1000 | NULL         |        1 |                      1 |                                0 |                                0 |                 2 |         0 | NULL             |
+-----------+-------------------------------------------+------------+--------------+--------------+------------------------+-------------------+--------------+----------+------------------------+----------------------------------+----------------------------------+-------------------+-----------+------------------+

mysql> desc sent_sms;
+------------+-----------------------+------+-----+---------+----------------+
| Field      | Type                  | Null | Key | Default | Extra          |
+------------+-----------------------+------+-----+---------+----------------+
| sql_id     | bigint(20)            | NO   | PRI | NULL    | auto_increment |
| momt       | enum('MO','MT','DLR') | YES  |     | NULL    |                |
| sender     | varchar(20)           | YES  |     | NULL    |                |
| receiver   | varchar(20)           | YES  |     | NULL    |                |
| udhdata    | blob                  | YES  |     | NULL    |                |
| msgdata    | text                  | YES  |     | NULL    |                |
| time       | bigint(20)            | YES  |     | NULL    |                |
| smsc_id    | varchar(255)          | YES  |     | NULL    |                |
| service    | varchar(255)          | YES  |     | NULL    |                |
| account    | varchar(255)          | YES  |     | NULL    |                |
| id         | bigint(20)            | YES  |     | NULL    |                |
| sms_type   | bigint(20)            | YES  |     | NULL    |                |
| mclass     | bigint(20)            | YES  |     | NULL    |                |
| mwi        | bigint(20)            | YES  |     | NULL    |                |
| coding     | bigint(20)            | YES  |     | NULL    |                |
| compress   | bigint(20)            | YES  |     | NULL    |                |
| validity   | bigint(20)            | YES  |     | NULL    |                |
| deferred   | bigint(20)            | YES  |     | NULL    |                |
| dlr_mask   | bigint(20)            | YES  |     | NULL    |                |
| dlr_url    | varchar(255)          | YES  |     | NULL    |                |
| pid        | bigint(20)            | YES  |     | NULL    |                |
| alt_dcs    | bigint(20)            | YES  |     | NULL    |                |
| rpi        | bigint(20)            | YES  |     | NULL    |                |
| charset    | varchar(255)          | YES  |     | NULL    |                |
| boxc_id    | varchar(255)          | YES  |     | NULL    |                |
| binfo      | varchar(255)          | YES  |     | NULL    |                |
| meta_data  | text                  | YES  |     | NULL    |                |
| priority   | bigint(20)            | YES  |     | NULL    |                |
| foreign_id | varchar(255)          | YES  |     | NULL    |                |
+------------+-----------------------+------+-----+---------+----------------+
29 rows in set (0.00 sec)

**Comment by Roll72** [comment]
sent_sms is for MO/MT and DLR logs. smpp_user is for management of credit and route for the user.
the only information about the price of each sms sent is in the ksmpp logs. Not in the database, you right. But it is possible to parse this log file to insert information in one database.

**Comment by Roll72** [comment]
I retrieve an example from my own logs : 
2018-02-13 16:15:08 [6113] [9] INFO: SMPP[smpp6] Using default routing for +3112341234 to smppd6 for cost 1.000000

**Comment by riteshraor2k** [comment]
but this is info / even log , ksmpp dont provide acccess log , even message id generated from ksmppbox which is provided to esme does  not exist in sent_sms table or anywhere , then how we can map the  parse log , there has to be somethign common  to map and update the logs 
can you please elaborate for this

**Comment by Roll72** [comment]
The beauty of open source is that you could make this improvment by recompilation of the ksmpp in order to make a database insertion on the good time with your needed information. Personnaly, I have all the information in sent_sms which I reconciliate with the credit used in smpp_user. Perhaps you could ask kneodev for this improvement. I can do it if kneodev don't want to do.

**Comment by riteshraor2k** [comment]
Hi

Can you plz suggest what is needed to be done here to achieve the things

**Comment by Roll72** [comment]
take a look into the source : /ksmpp/smpp/libsmpp is a good start. Take a look on the word "deduct" and you will see the mechanism. If it is too complex or you are not familiar with C, you could send me a private email then I can make a quote for this work.

**Comment by riteshraor2k** [comment]
What is ur email address?

**Comment by Roll72** [comment]
give me yours.

**Comment by riteshraor2k** [comment]
raoritesh231@gmail.com

**Comment by riteshraor2k** [comment]
Hi  Roll72 

you didnt sent me email  , i m waiting for your email

**Comment by veduyu** [comment]
i haven't use sqlbox but still message is not stored in the smpp_store table. what should i do please help

**Comment by Roll72** [comment]
I assume smpp_store table is only to store DLR or SMS to send in case of the route is down or the client is not connected. It is a temporary table. If you want a complete trace of sms, use sqlbox.

**Comment by veduyu** [comment]
Hi @Roll72 thanks for you reply. But i am not able to route through smpp_route. can you help me regarding this.

**Comment by ib1corp** [comment]
Hi @Roll72, while sending messages, the smpp_route table regex are not working, if i leave the regex column blank, that paricular smsc_id gets used, otherwise the default smsc_id from smpp_user gets used. the numbers don't match the regex in the routing table (smpp_route). 
im not sure where im making a mistake.

Also, for logging of message, if i use sqlbox in between, only the DLR gets inserted into the sent_sms table, this data is incomplete as far as the msgdata (Message) is concerned becuase the column msgdata does not contain the full message. I could not find  MT messages being logged in the sqlbox sent_sms table, onle DLR (MO) messages get logged. Could someone let me know where im making mistakes.

Also, we require several customization's, if there is anyone here who is good at C and is willing to do if for us with professional fees/freelance professional coding/development,  please urgently get in touch @ ibonecorp (at) gmail (dot) com

**Comment by kneodev** [comment]
Check your kannel bearerbox configuration, it requires allowed-smsc-id to be set
