### ISSUE TITLE
data not inserted in smpp_store

### ISSUE THREAD

**Issue by veduyu** [kneodev/ksmppd#80]
Everything is working fine, but i was not able to see data in the smpp store. where does the message go and how can i see the message data and its dlr.

**Comment by ib1corp** [comment]
route it through sqlbox

**Comment by veduyu** [comment]
@ib1corp thanks for the reply. i have used sqlbox in-between ksmppd and bearerbox, to track the messages, but i have a question that how can i log no-credit and other ksmppd generated logs on sqlbox.

**Comment by ib1corp** [comment]
loggin into mysql is not inbuild in this code..u need to customize it....alternatively, u can parse the .log file to capture the messages...

**Comment by kneodev** [comment]
You can use the http filter or pluginbox for these

**Comment by veduyu** [comment]
thanku @kneodev can u suggest me how can i filter DND and spam, before sending the message
