### ISSUE TITLE
can anyone explain me how smpp_store and smpp_route works?

### ISSUE THREAD

**Issue by veduyu** [kneodev/ksmppd#81]
everything works fine as explained in the example configuration but i was not able to see the messages in the smpp_store table, and also not able to route the message through smpp_route table. please help me regarding this.

**Comment by ib1corp** [comment]
have a look at the wiki : https://github.com/kneodev/ksmppd/wiki

smpp_store table is a temporary parking table, when outbound smpp connections are down or when there is excess queue, the messages are queued in this table for processing.
