### ISSUE TITLE
Delivery Reports

### ISSUE THREAD

**Issue by smppuser** [kneodev/ksmppd#87]
Hi,

My smpp users are getting codes and FIDs which are different from the codes I am receiving directly from my operator. I got delivered status from my operator. But my smpp user got undelivered status. How is this happening?

**Comment by smppuser** [comment]
Hi,.... Any Updates????????

**Comment by smppuser** [comment]
Any Updates?

**Comment by coinhosting** [comment]
hi, 

cross check DLR CODE maping at esme level 

thanks

**Comment by smppuser** [comment]
My smpp user should get the same DLR report as what I am getting from the operator. But it is not happening. What will be the reason? From where my smpp user get the Error codes?

**Comment by donald-jackson** [comment]
No they shouldn't, ksmppd creates its own message ID and maps it
