### ISSUE TITLE
More than 160 characters

### ISSUE THREAD

**Issue by smppuser** [kneodev/ksmppd#89]
If we send a messages with more than 160 characters long will there be two FIDs and Two delivery reports will receive from the operator?

**Comment by ib1corp** [comment]
Hi, we were struggling with kannel and the open source smpp servers all these years.

Finally we have developed our own In-house SMPP Server fully built on node.js & nosql technology. It has a capacity of validating DND Numbers/Blacklist/Spam/Intelligent Routing/SenderId based routing etc and a benchmark tested validation speed of 25+ Lakh message validations per second. SMPP TPS is scale-able to several thousand TPS. If anyone is interested in enterprise grade smpp server with the ability to shed a high budget/price, please contact me "iwebpush" at gmail dot com

**Comment by kneodev** [comment]
yes

**Comment by smppuser** [comment]
But at our end, only one FID is there. See the logs below. This is how a double credit message goes to the operator. We get only one FID and one DLR for it. What should we do to get different FIDs for each Message sent?

2018-07-02 09:10:10 Sent SMS [SMSC:xxxx] [SVC:xxxx] [ACT:] [BINF:2] [**FID:S21311185020910103124841412**] [META:?smpp?] [from:xxxx] [to:xxxxx] [flags:-1:0:-1:0:19] [msg:153:messag first part] [udh:6:050003760201]

2018-07-02 09:10:10 Sent SMS [SMSC:xxxx] [SVC:xxxx] [ACT:] [BINF:2] [### FID:] [META:?smpp?] [from:xxxx] [to:xxxx] [flags:-1:0:-1:0:0] [msg:129:message 2nd part] [udh:6:050003760202]

**Comment by kneodev** [comment]
this is the way kannel bearerbox deals with the messages, not ksmppd.

ksmppd is a simple relay/communication layer and submits and received to kannel as is.
