### ISSUE TITLE
KSMPPD Outgoing SMS Submission

### ISSUE THREAD

**Issue by name256** [kneodev/ksmppd#92]
Hello,
I am working on a project where I need to receive messages from different clients to be transmitted on to end users. 
I was able to download and install your product and used the example ksmppd.conf to create my own confirg. The config is working well and is able to bind to an external SMPP client and receive messages submitted to it from the client. I am however unable to submit the same messages to a bound kannel to send the subsequent messages to my end clients. Kindly assist as I may be missing something on the configs which I have attached.

Kindly assist as I am not seeing any errors in my kannel logs from the instance that is bound to send messages to users phones.

[ksmppd.conf.txt](https://github.com/kneodev/ksmppd/files/2131132/ksmppd.conf.txt)
[kannel.conf.txt](https://github.com/kneodev/ksmppd/files/2131133/kannel.conf.txt)

**Comment by kneodev** [comment]
please refer to kannel users mailing list
