### ISSUE TITLE
DLR Issue - not been sent to ESME's

### ISSUE THREAD

**Issue by voicecomms** [kneodev/ksmppd#93]
Hello,

I am running instance of ksmppd and is working well but the dlr is not being pushed to the esme's , is there any settings to push the dlr's ?

Best Regards 
Chetan Jha

**Comment by voicecomms** [comment]
Hello Any thing on the above issue

**Comment by thesanthosh** [comment]
Hello @voicecomms,
Basically, Ksmppd automatically processes the DLR's instantly when it arrives at your SMSC.
Can you cross reference your SMSC whether DLRS received at kannel first?
if possible do share the logs to assist quickly.

**Comment by voicecomms** [comment]
Hello,

Yes the DLR's are coming in mysql dlr tables I can see all the entries. Please let me know which logs you need I will share the same.

Best Regards 
Chetan Jha

**Comment by thesanthosh** [comment]
Can you share your submission logs for your ESME user kannel -> ksmppd -> kannel local SMSC submit_sm logs.
Can you cross check the SMPP DB table by name smpp_store for any pending DLR's in the queue?

**Comment by voicecomms** [comment]
The smpp_store does not shows any entries, I will send the logs in a while

**Comment by coinhosting** [comment]
kindly confirm if ESME bind in TX or TR or TRX mode for sending DLR TR or TRX is required

**Comment by voicecomms** [comment]
Issues Resolved was from SMSC config in kannel.conf,  reconfigured in trx mode and its routing dlr's now.

Thanks for assistance 

Regards
CJ
