### ISSUE TITLE
reject message using http routing - headers required

### ISSUE THREAD

**Issue by ib1corp** [kneodev/ksmppd#97]
Hi @kneodev

What does this header mean: X-KSMPPD-Route-Status: ?

If i send a zero value : X-KSMPPD-Route-Status: 0
then will the message get rejected?

I need to reject messages after blacklisting, please let me know which hear is to be used to reject a message.
Also, i there any head to send custom error code for rejected message.

please help.

**Comment by ib1corp** [comment]
To reject messages, I tried using X-KSMPPD-Route-Status: 0

Ksmppd routed the message from default route instead of rejecting it.

See the logs below:

2018-07-13 21:06:46 [32549] [19] WARNING: X-KSMPPD-Route-Status indicated routing failure (code 0), rejecting
2018-07-13 21:06:46 [32549] [19] DEBUG: MySQL deducting credit from smppusera value 1.000000
2018-07-13 21:06:46 [32549] [19] INFO: SMPP[smppusera] Using default routing for +919999999999 to 400 for cost 1.000000
2018-07-13 21:06:46 [32549] [6] DEBUG: BB[t91_smpp_server] Adding be77b60d-d43c-4946-93e0-0ce325dfd345 to open acks

Please let me know what to do so that i can reject a message with a custom error code.

**Comment by ib1corp** [comment]
hi @kneodev 
can u please let mke know what headers to return for rejecting messages.
when i return  "X-KSMPPD-Route-Status: 0" , message gets routed through default route.

I want to reject it. please let me know how to do it.

**Comment by ib1corp** [comment]
Alright, i found the solution, im able to reject a message by returning "X-KSMPPD-Route-Status: 0" and having a null value for default route. If a default route is set, it gets routed through default route irrespective of the status header.
Also, im able to return a custom error code for rejection by using this: X-KSMPPD-Route-Error-Code : (integer/errorcode)

However, the rejection happens at submit_sm level itself, it does not process the message at all and rejects it with an error code with submit_sm_resp. Hence, it also does not log the message into sqlbox as well (if we route it through sqlbox).

What i was actually looking for is to reject a message and return a custom reject error code as deliver_sm with proper messageid, and also deduct the balance using the cost headers.

@kneodev 
If there is any option to reject message with custom error code as delivery report/ deliver_sm, please do let me know.

**Comment by kneodev** [comment]
no sorry, thats not the way SMPP works.

create a custom SMSC which can do this kludge

**Comment by manojr2k** [comment]
> Alright, i found the solution, im able to reject a message by returning "X-KSMPPD-Route-Status: 0" and having a null value for default route. If a default route is set, it gets routed through default route irrespective of the status header.
> Also, im able to return a custom error code for rejection by using this: X-KSMPPD-Route-Error-Code : (integer/errorcode)
> 
> However, the rejection happens at submit_sm level itself, it does not process the message at all and rejects it with an error code with submit_sm_resp. Hence, it also does not log the message into sqlbox as well (if we route it through sqlbox).
> 
> What i was actually looking for is to reject a message and return a custom reject error code as deliver_sm with proper messageid, and also deduct the balance using the cost headers.
> 
> @kneodev
> If there is any option to reject message with custom error code as delivery report/ deliver_sm, please do let me know.


HI how you set the default route Null?

**Comment by adeshas** [comment]
He is using the database for authentication and http for routing. There is a 'default_smsc' column. You can set it to NULL (without any quotes). Then set the status ("X-KSMPPD-Route-Status: 0") to 0 in your HTTP routing. it works for me.
