### ISSUE TITLE
Compatibility with Kannel 1.4.5

### ISSUE THREAD

**Issue by ib1corp** [kneodev/ksmppd#98]
Hi @kneodev ,
Is ksmppd compatible/stable with kannel 1.4.5
can we start using with this new version?

**Comment by donald-jackson** [comment]
yes

**Comment by ib1corp** [comment]
im having difficulty to install ksmppd.
using kannel 1.4.5 stable release.

root@smpp-ubuntu-s-2vcpu-4gb-1-01:# git clone https://github.com/kneodev/ksmppd.git
root@smpp-ubuntu-s-2vcpu-4gb-1-01:# cd ksmppd
root@smpp-ubuntu-s-2vcpu-4gb-1-01:~/ksmppd# ./bootstrap.sh
You need svn on your $PATH to build ksmppd

Also, if i use the autoconf option, i get this issue:
root@smpp-ubuntu-s-2vcpu-4gb-1-01:# git clone https://github.com/kneodev/ksmppd.git
root@smpp-ubuntu-s-2vcpu-4gb-1-01:# cd ksmppd
root@smpp-ubuntu-s-2vcpu-4gb-1-01:~/ksmppd# autoreconf -iv
autoreconf: 'configure.ac' or 'configure.in' is required

where am i going wrong? someone please help.
